### PR TITLE
remove discoveryv1beta1 from e2e tests

### PR DESCRIPTION
**Pull request by nojnhuh**
Non-ancient versions of Kubernetes (1.22-ish? and later) do not serve `v1beta1` of the discovery APIs which include EndpointSlices. This PR removes logic dealing with that API version, which was only present in the connectivity e2e test.

### CODE REVIEW

**Comment by jackfrancis** [comment]
@skitt can we merge this?

**Comment by jackfrancis** [comment]
@lauralorenz @JeremyOT I think we should be able to merge this one?

**Comment by skitt** [comment]
> @skitt can we merge this?

Yes, and I’ll be able to take care of it once #56 is merged :wink:.

**Comment by jackfrancis** [comment]
Congrats @skitt on being promoted to the critical path! 😜

**Comment by jackfrancis** [comment]
I think https://github.com/kubernetes-sigs/mcs-api/pull/53 supercedes this, not sure this is needed. Let's wait for @nojnhuh to return from vacation and he can close this out, if true.

**Comment by jackfrancis** [comment]
@nojnhuh literally commented as such here: https://github.com/kubernetes-sigs/mcs-api/pull/53#discussion_r1693356186 :)

Whomever has perms can close this PR, it's no longer relevant.

**Comment by skitt** [comment]
Thanks @jackfrancis, I had this on my todo list for today :wink:!

**Pull request closed without merging**
